### ISSUE TITLE
Amounts over $999 showing up as $1

### ISSUE THREAD

**Issue by sgpeter1** [IridescentShadow/ynab-discover-converter#1]
Made some large purchases and payments this last round and those with amounts over $999 were showing up as $1 in the OFX. I suspect it's something to do with the commas in the amount, e.g., $1,000.

Thanks for this tool! I toyed with writing something myself, but now I don't have to. Here's hoping this is only needed temporarily.

**Comment by IridescentShadow** [comment]
Thanks for letting me know about this. I just pushed a patch up that strips the commas out. Give it another try and let me know if it's indeed working. Unfortunately I don't have any sample exports with a purchase that large to test.

**Comment by sgpeter1** [comment]
The values are showing properly now for amounts greater than >= $1000.

![image](https://user-images.githubusercontent.com/20599459/201498926-721cad2d-f7f8-4f00-b778-b0fc53d004ab.png)
